# fly.toml file for seh-nya Flask app
app = "seh-nya"
primary_region = "iad"

[build]
  # Using Dockerfile in project root

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "requests"
    soft = 20
    hard = 40

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

