[build]
builder = "nixpacks"
buildCommand = "bun install && bun run build"

[deploy]
startCommand = "bun run ./src/server/index.ts"
healthcheckPath = "/api/hello"   # safer healthcheck, since / may 404 in CI

[env]
SERVE_INDEX = "dist"
