# Railway deployment configuration for Bun + React + Tailwind app

[build]
# Use Nixpacks builder and run Bun install + build
builder = "NIXPACKS"
buildCommand = "bun install && bun run build"

[deploy]
# Start the Bun server; Railway will provide PORT env var which the server uses
startCommand = "bun start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
