name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Railway Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.34

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Set up Node (for NPM, optional)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Deploy via Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} || true
          railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }}
